services:
  - type: web
    name: cloud-control-to-major-tom
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false 